### ISSUE TITLE
Check if the lock is taken

### ISSUE THREAD

**Issue by rhutanu90** [php-lock/lock#21] opened 2018-06-05 15:46 UTC
Hi! We encountered a situation when we would like to terminate all the calls when a locked call is already in execution (instead of waiting). @malkusch do you plan to extend the library with this feature in the near future? :+1:

**Comment by willemstuursma** [comment] 2018-06-05 18:22
You mean, testing if the lock is taken, and then aborting?

**Comment by TheLevti** [comment] 2018-06-06 06:44
That would also be a solution. We use predis locks. In some cases we don't want to wait until the lock is released, but abort the request if another process is already holding that lock.

**Comment by rhutanu90** [comment] 2018-06-06 07:04
Yes, check if the lock is taken and if so throw an exception

**Comment by tsmgeek** [comment] 2020-01-03 13:26
If the Loop class had an ability to pass a flag to disable retries or set X retries instead of using timeout this could help this out etc.

**Comment by georgegg** [comment] 2020-09-21 16:53
Hi. I would avoid to introduce a second timeout because funky things might happen. I would suggest the use of a flag to enable/disable the loop to execute more than once or till the locks ttl expire. 
Is this thread active or rather do you see value in this feature?

**Comment by fredericgboutin-yapla** [comment] 2024-03-19 17:53
"workaround", use Symfony Lock instead - https://symfony.com/doc/5.x/components/lock.html#usage

**Comment by mvorisek** [comment] 2024-12-02 12:03
closing as duplicate of #11

**Closed by mvorisek** 2024-12-02 12:03 UTC
